services:
  rt:
    build: ./rt
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      RMQ_USER: ${RMQ_USER}
      RMQ_PASS: ${RMQ_PASS}
      RMQ_HOST: rmq
  grader:
    build: ./grader
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      RMQ_USER: ${RMQ_USER}
      RMQ_PASS: ${RMQ_PASS}
      DB_HOST: db
      RMQ_HOST: rmq
  db:
    image: postgres:17-alpine # alpine cuz my laptop is running out of mem :(
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - dbdata:/var/lib/postgresql/data
  rmq:
    image: rabbitmq:3-alpine
    restart: unless-stopped
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASS}
    volumes:
      - rmqdata:/var/lib/rabbitmq
volumes:
  dbdata:
  rmqdata:
